[package]
name = "mend"
version = "0.1.0"
authors = ["George Kulakowski <george.kulakowski@gmail.com>"]
edition = "2018"
description = "mend"
license = "MIT/Apache-2.0"
repository = "https://github.com/kulakowski/mend.git"
